# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a31833ee8b8ab4a393d8d2fd8ec0b1fc5167541b115c29a393b4dc0e7e465c541c0b985bdfe1efc53859ec275c417a6eb943a2c61779fa1d2d51ff1b129d3d

test:
  secret_key_base: 692b583e4e439c42e59f394cfd9a7ec05865d33adf694b8d19a786fed7af35281499981511775f84dead4cc86577191f3f3cf61fde3257b0087310cbc5febcd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
